tencent.cos.secretId=${SECRETID}
tencent.cos.secretKey=${SECRETKEY}
tencent.cos.bucket-name=${BUCKETNAME}
tencent.cos.region=${REGION}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=300MB
logging.level.com.qcloud.cos=ERROR

server.tomcat.connection-timeout=600000
server.tomcat.keep-alive-timeout=600000
server.servlet.session.timeout=1h

spring.datasource.url=jdbc:mysql://localhost:3306/pdf_split?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT-8
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

